version: '3.7'

services:

  # backend
  app-server:
    image: app-server:latest
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - app-db  
    networks:
      - backend
      - frontend

  # frontend
  app-client:
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "80:80"
    depends_on:
      - app-server
    networks:
      - frontend
      
  # admin
  app-admin:
    build:
      context: admin-dashboard
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080/api
    ports:
      - "81:81"
    depends_on:
      - app-server
    networks:
      - frontend  

  # Database Service (MySQL)
  app-db:
    image: mysql
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: system
      MYSQL_PASSWORD: system
      MYSQL_DATABASE: app_db
    networks:
      - backend

# Networks
networks:
  backend:
  frontend:

# Volumes
volumes:
  db:  